 spring:
  datasource:
    db1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.56.10:23306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    db2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.56.10:23306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.56.10/MyData?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
 socketio:
   host: localhost
   port: 8083
   # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
   maxFramePayloadLength: 1048576
   # 设置http交互最大内容长度
   maxHttpContentLength: 1048576
   # socket连接数大小（如只监听一个端口boss线程组为1即可）
   bossCount: 1
   workCount: 100
   allowCustomRequests: true
   # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
   upgradeTimeout: 1000000
   # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
   pingTimeout: 6000000
   # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
   pingInterval: 25000